### ISSUE TITLE
SSLError on startup

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc/polyglot-v2-python-interface#13]
This was reported as an error for a cold start.

```
2019-05-16 02:07:44,023 [Controller] [ERROR] Ecobee Controller:get: Connection error for https://api.ecobee.com/1/thermostatSummary: HTTPSConnectionPool(host='api.ecobee.com', port=443): Max retries exceeded with url: /1/thermostatSummary?json=%7B%22selection%22%3A+%7B%22selectionMatch%22%3A+%22%22%2C+%22selectionType%22%3A+%22registered%22%2C+%22includesEquipmentStatus%22%3A+true%7D%7D (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x75bf1c50>, 'Connection to api.ecobee.com timed out. (connect timeout=60)'))
2019-05-16 02:07:44,027 [Controller] [ERROR] Thermostats instance wasn't dictionary. Skipping...
2019-05-16 13:01:59,996 [MainThread] [INFO ] Received Config from STDIN.
2019-05-16 13:02:00,009 [MainThread] [INFO ] UDI Polyglot v2 Interface 2.0.29 Starting...
2019-05-16 13:02:02,630 [Interface ] [INFO ] Connecting to MQTT... localhost:1883
2019-05-16 13:02:02,635 [Interface ] [ERROR] MQTT Connection error: An exception of type SSLError occurred. Arguments:
(1, 'getrandom() initialization failed. (_ssl.c:720)')
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 325, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/pi/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 1566, in loop_forever
    self.reconnect()
  File "/home/pi/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 994, in reconnect
    sock.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: getrandom() initialization failed. (_ssl.c:720)
2019-05-16 13:02:0
```

**Comment by jimboca** [comment]
Just go this again:

```
2019-10-27 12:47:52,689 [MainThread] [INFO ] Controller:init: Initializing HueEmulator Controller 2.0.8
2019-10-27 12:47:52,713 [Interface ] [ERROR] Exception in thread Interface:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/polyinterface/polyinterface.py", line 334, in _startMqtt
    self._mqttc.loop_forever()
  File "/home/pi/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 1566, in loop_forever
    self.reconnect()
  File "/home/pi/.local/lib/python3.5/site-packages/paho/mqtt/client.py", line 994, in reconnect
    sock.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: getrandom() initialization failed. (_ssl.c:720)
```
